config/routes.rb
Rails.application.routes.draw do

    resources :contacts do
        collection do
            post :confirm
            get :thankyou
        end
    end

    root 'contacts#new'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord

    enum contact_type: {
        '商品について': 1,
        '注文について': 2,
        'キャンセルについて': 3,
        '配送について':4,
        'サービスについて': 5
    }

    validates :name, presence: true
    validates :email, presence: true
    validates :content, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

    def index
        @contacts = Contact.all.order(created_at: 'desc')
    end

    def new
        @contact = Contact.new
    end

    def confirm
        @contact = Contact.new(contact_params)

        if @contact.valid?
            render :confirm
        else
            render :new
        end
    end

    def create

        if params[:back]
            @contact = Contact.new(contact_params)
            render :new
        else
            @contact = Contact.create(contact_params)

            redirect_to action: 'thankyou'
        end
    end

    def thankyou
    end

    def contact_params
        params.require(:contact).permit(:name, :email, :contact_type, :content)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/contacts/confirm.html.erb
<div>
    <div>

        <div>
            <label for="input_name" class="control-label">名前</label>
            <div>
                <%= @contact.name %>
            </div>
        </div>

        <div>
            <label for="input_email" class="control-label">メールアドレス</label>
            <div>
                <%= @contact.email %>
            </div>
        </div>

        <div>
            <label for="input_contact_type" class="control-label">問い合わせ種類</label>
            <div>
                <%= @contact.contact_type %>
            </div>
        </div>

        <div>
            <label for="input_content" class="control-label">問い合わせ内容</label>
            <div>
                <%= simple_format(h(@contact.content)) %>
            </div>
        </div>

        <%= form_for @contact, url: contacts_path, html: {method: "post"} do |f|  %>
            <%= f.hidden_field :name %>
            <%= f.hidden_field :email %>
            <%= f.hidden_field :contact_type %>
            <%= f.hidden_field :content %>

            <div>
                <div class="submit-btn">
                    <%= f.submit '戻る', name: 'back', class: 'btn btn-default btn-back btn-block' %>
                    <%= f.submit '送信', class: 'btn btn-default btn-block' %>
                </div>
            </div>

        <% end %>
    </div>
</div>

app/views/contacts/index.html.erb
<table class="table table-striped">
    <tr>
        <th>問い合わせ日時</th>
        <th>名前</th>
        <th>メールアドレス</th>
        <th>問い合わせ種類</th>
        <th>問い合わせ内容</th>
    </tr>

    <% @contacts.each do |contact| %>
    <tr>
        <td><%= l contact.created_at, format: :short %></td>
        <td><%= contact.name %></td>
        <td><%= contact.email %></td>
        <td><%= contact.contact_type %></td>
        <td><%= simple_format(h(contact.content)) %></td>
    </tr>
    <% end %>
</table>

app/views/contacts/new.html.erb
<div>
    <div>

        <%= form_for @contact, url: confirm_contacts_path, html: {method: "post"} do |f|  %>

        <% if @contact.errors.any? %>
          <div class="alert-danger">
            <p><%= @contact.errors.count %>件のエラーがあります</p>

            <ul>
            <% @contact.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
            </ul>
          </div>
        <% end %>

        <div>
            <label for="input_name" class="control-label">名前</label>
            <div>
                <%= f.text_field :name, class: 'form-control', id: 'login_name', placeholder: 'Name' %>
            </div>
        </div>

        <div>
            <label for="input_email" class="control-label">メールアドレス</label>
            <div>
                <%= f.email_field :email, class: 'form-control', id: 'login_name', placeholder: 'example@gmail.com' %>
            </div>
        </div>

        <div>
            <label for="input_contact_type" class="control-label">問い合わせ種類</label>
            <div>
                <%= f.select :contact_type, Contact.contact_types.keys.to_a, {}, class: 'form-control' %>
            </div>
        </div>

        <div>
            <label for="input_content" class="control-label">問い合わせ内容</label>
            <div>
                <%= f.text_area :content %>
            </div>
        </div>

        <div>
            <div class="submit-btn">
                <%= f.submit '確認', class: 'btn btn-default btn-block' %>
            </div>
        </div>

        <% end %>

    </div>
</div>

app/views/contacts/thankyou.html.erb
<p>お問い合わせありがとうございました</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>Work</title>
        <%= csrf_meta_tags %>

        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    </head>

    <body>
        <div class="container">
            <h1>お問い合わせ</h1>

            <div class="menu">
                <%= link_to 'お問い合わせフォーム', new_contact_path, class: 'btn btn-default' %></li>
                <%= link_to 'お問い合わせ一覧', contacts_path, class: 'btn btn-default' %></li>
            </div>

            <%= yield %>
        </div>
    </body>
</html>